prefix = "."
stop-words = "datasets/stopwords.txt"

dataset = "datasets"
corpus = "line.toml"
index = "idx"

query-judgements = "datasets/cranfield/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "datasets/cranfield/cranfield-queries.txt"
query-id-start = 1


[params-tuner]
logging-level = 0
split-ratio = 0.8
cv = 3
